/* Script DML: COUNTS de todas las tablas*/
SELECT COUNT(*) FROM TIPO_EMPLEADO;
SELECT COUNT(*) FROM PAIS;
SELECT COUNT(*) FROM CIUDAD;
SELECT COUNT(*) FROM DIRECCION;
SELECT COUNT(*) FROM TIENDA;
SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) FROM CUENTA;
SELECT COUNT(*) FROM EMPLEADO;
SELECT COUNT(*) FROM CATEGORIA;
SELECT COUNT(*) FROM CLASIFICACION;
SELECT COUNT(*) FROM IDIOMA;
SELECT COUNT(*) FROM ACTOR;
SELECT COUNT(*) FROM PELICULA;
SELECT COUNT(*) FROM ASIGNACION_CATEGORIA;
SELECT COUNT(*) FROM ASIGNACION_ACTOR;
SELECT COUNT(*) FROM ASIGNACION_PELICULA_TIENDA;
SELECT COUNT(*) FROM RENTA;



