/* Script DDL: Borrado y Creado de la Tabla Temporal */

CREATE TABLE TMP(
	NOMBRE_CLIENTE         VARCHAR(300) NULL,
	CORREO_CLIENTE         VARCHAR(300) NULL,
	CLIENTE_ACTIVO         VARCHAR(300) NULL,
	FECHA_CREACION         VARCHAR(300) NULL,
	TIENDA_PREFERIDA       VARCHAR(300) NULL,
	DIRECCION_CLIENTE      VARCHAR(300) NULL,
	CODIGO_POSTAL_CLIENTE  VARCHAR(300) NULL,
	CIUDAD_CLIENTE         VARCHAR(300) NULL,
	PAIS_CLIENTE           VARCHAR(300) NULL,
	FECHA_RENTA            VARCHAR(300) NULL,
	FECHA_RETORNO          VARCHAR(300) NULL,
	MONTO_A_PAGAR          VARCHAR(300) NULL,
	FECHA_PAGO             VARCHAR(300) NULL,
	NOMBRE_EMPLEADO        VARCHAR(300) NULL,
	CORREO_EMPLEADO        VARCHAR(300) NULL,
	EMPLEADO_ACTIVO        VARCHAR(300) NULL,
	TIENDA_EMPLEADO        VARCHAR(300) NULL,
	USUARIO_EMPLEADO       VARCHAR(300) NULL,
	CONTRASENIA_EMPLEADO   VARCHAR(300) NULL,
	DIRECCION_EMPLEADO     VARCHAR(300) NULL,
	CODIGO_POSTAL_EMPLEADO VARCHAR(300) NULL,
	CIUDAD_EMPLEADO        VARCHAR(300) NULL,
	PAIS_EMPLEADO          VARCHAR(300) NULL,
	NOMBRE_TIENDA          VARCHAR(300) NULL,
	ENCARGADO_TIENDA       VARCHAR(300) NULL,
	DIRECCION_TIENDA       VARCHAR(300) NULL,
	CODIGO_POSTAL_TIENDA   VARCHAR(300) NULL,
	CIUDAD_TIENDA          VARCHAR(300) NULL,
	PAIS_TIENDA            VARCHAR(300) NULL,
	TIENDA_PELICULA        VARCHAR(300) NULL,
	NOMBRE_PELICULA        VARCHAR(300) NULL,
	DESCRIPCION_PELICULA   VARCHAR(300) NULL,
	ANIO_LANZAMIENTO       VARCHAR(300) NULL,
	DIAS_RENTA             VARCHAR(300) NULL,
	COSTO_RENTA            VARCHAR(300) NULL,
	DURACION               VARCHAR(300) NULL,
	COSTO_POR_DANIO        VARCHAR(300) NULL,
	CLASIFICACION          VARCHAR(300) NULL,
	LENGUAJE_PELICULA      VARCHAR(300) NULL,
	CATEGORIA_PELICULA     VARCHAR(300) NULL,
	ACTOR_PELICULA         VARCHAR(300) NULL
);

DROP TABLE TMP;


\COPY TMP FROM 'C:\Users\wrm\Desktop\[BD1]Practica3_200915518\Original.csv' DELIMITER ';' CSV;
DELETE FROM TMP WHERE TMP.PAIS_CLIENTE = 'PAIS_CLIENTE';

SELECT COUNT(*) FROM TMP;

/* Entrar a POSTGRES 

psql -U postgres
abc123
\c PR3 

*/



